[colors.bright]
black = "#928374"
blue = "#83A598"
cyan = "#8EC07C"
green = "#B8BB26"
magenta = "#D3869B"
red = "#FB4934"
white = "#EBDBB2"
yellow = "#FABD2F"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689D6A"
green = "#88881A"
magenta = "#B16286"
red = "#CC241D"
white = "#A89984"
yellow = "#D79921"

[colors.primary]
background = "#282828"
foreground = "#eaeaea"

[font]
size = 10.0

[font.bold]
family = "FiraCode Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Propo"
style = "BoldItalic"

[font.italic]
family = "Hermit"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Propo"

[window]
opacity = 0.7

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 2
y = 2
