#!/bin/sh

# Example for ~/.config/sxiv/exec/image-info
# Called by sxiv(1) whenever an image gets loaded,
# with the name of the image file as its first argument.
# The output is displayed in sxiv's status bar.

s=" | " # field separator
filename=$(basename "$1")
# filesize=$(du -Hh "$1" | cut -f 1)
# 
# # The '[0]' stands for the first frame of a multi-frame file, e.g. gif.
# geometry=$(identify -format '%wx%h' "$1[0]")
# 
# tags=$(exiv2 -q pr -pi "$1" | awk '$1~"Keywords" { printf("%s,", $4); }')
# tags=${tags%,}
# 
# echo "${filesize}${s}${geometry}${tags:+$s}${tags}${s}${filename}"

expsure_time=$(exiv2 "$1"| grep "^Exposure time"  | awk -F':' '{print $2}' | sed 's/ //g')
aperture=$(exiv2 "$1"| grep "^Aperture"  | awk -F':' '{print $2}' | sed 's/ //g')
iso=ISO$(exiv2 "$1"| grep "^ISO speed"  | awk -F':' '{print $2}' | sed 's/ //g')
focal_length=$(exiv2 "$1"| grep "^Focal length"  | awk -F':' '{print $3}' | sed 's/ //g'|sed 's/)//g')
flash=$(exiv2 "$1" | grep "Flash\ * :"  | awk -F',' '{print $1}' | sed 's/ //g')
echo "${filename}${s}${expsure_time}${s}${aperture}${s}${iso}${s}${focal_length}${s}${flash}"
